env:
  - GO111MODULE=on

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - tip

matrix:
  allow_failures:
    - go: tip

before_script:
	- test $TRAVIS_BRANCH = "master" && curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash

script:
  - go get -t -v ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - test $TRAVIS_BRANCH = "master" && fossa init
  - test $TRAVIS_BRANCH = "master" && fossa analyze

after_success:
  - ./scripts/deploy_to_docker.sh

before_deploy:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GH_KEY
  file_glob: true
  file: build/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  webhooks: 
    urls:
      - https://tgwh.goca.io/travisci
    on_success: always
    on_failure: always